import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Space_Grotesk } from "next/font/google";

import "./globals.css";
import Providers from "@/providers/Provider";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme/theme-provider";
import NavbarAndFooterProvider from "@/providers/NavbarAndFooterProvider";

// const inter = Inter({ subsets: ["latin"] });

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
       
    <html lang="en">
      <body className={spaceGrotesk.className}>
      <ThemeProvider 
         attribute="class"
         defaultTheme="system"
         enableSystem
         disableTransitionOnChange
      >
        <Toaster />
     <NavbarAndFooterProvider>
     {children}
     </NavbarAndFooterProvider>
      
      
      </ThemeProvider>
      </body>
    </html>
    
    </Providers>
  );
}
